// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnsrokcjgrzvndkmuytj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imduc3Jva2NqZ3J6dm5ka211eXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDk1NTksImV4cCI6MjA2OTcyNTU1OX0.wfRdjyt-Q0znxzu1KbHe2UQF2izRyC1Hi-xSys8y4a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});